### ISSUE TITLE
 Index creation failed: mapper_parsing_exception: Failed to parse mapping : Field [_id] is defined twice 

### ISSUE THREAD

**Issue by skonsoft** [sineflow/ElasticsearchBundle#3]
Hello,

I followed exactly the docs to create a very basic example document, but it won't parse it with errir:

> Index creation failed: mapper_parsing_exception: Failed to parse mapping [country]: Field [_id] is defined twice in [country]

My configuration is:

```
sineflow_elasticsearch:
    connections:
        default:
            hosts: [127.0.0.1:9200]           
    indices:
        countries:
            name: afariat_country
            connection: default
            types:
                - SkonsoftModelBundle:Country
```

And my document definition:

```
<?php

namespace Skonsoft\ModelBundle\Document;

use Sineflow\ElasticsearchBundle\Document\AbstractDocument;
use Sineflow\ElasticsearchBundle\Annotation as ES;

/**
 * @ES\Document(type="country")
 *
 * @author skander
 */
class Country extends AbstractDocument
{
    /**
     * @var string
     * 
     * @ES\Property(name="name", type="string")
     *
     */
    public $name;

    /**
     * @var string
     *
     * @ES\Property(name="isoCode", type="string")
     */
    public $isoCode;

}

```

When i run command:
`app/console sineflow:es:index:create countries`

I got this error:

> Index creation failed: mapper_parsing_exception: Failed to parse mapping [country]: Field [_id] is defined twice in [country]

Have you any idea it won't work ?

Thank you.
